---
# Ansible Galaxy Collections Requirements
# Install with: ansible-galaxy collection install -r requirements.yml

collections:
  - name: community.general
    version: ">=8.0.0"
  - name: community.zabbix
    version: ">=2.0.0"

