---
- name: Read CSV file
  set_fact:
    zbx_csv_lines: "{{ lookup('file', zbx_migration_csv).splitlines() }}"

- name: Parse CSV header
  set_fact:
    zbx_csv_header: "{{ zbx_csv_lines[0].split(',') | map('trim') | list }}"

- name: Build records from CSV lines
  set_fact:
    zbx_records: "{{ zbx_records | default([]) + [ dict(zip(zbx_csv_header, (item.split(',', zbx_csv_header|length - 1) | map('trim') | list))) ] }}"
  loop: "{{ zbx_csv_lines[1:] }}"

- name: Zabbix login to obtain auth token (if not provided)
  when: zabbix_auth | length == 0
  uri:
    url: "{{ zabbix_url }}"
    method: POST
    body_format: json
    validate_certs: "{{ zabbix_validate_certs }}"
    body:
      jsonrpc: "2.0"
      method: "user.login"
      params:
        username: "{{ zabbix_user }}"
        password: "{{ zabbix_password }}"
      id: 0
  register: zbx_login_resp

- name: Set zabbix_auth from login
  when: zabbix_auth | length == 0
  set_fact:
    zabbix_auth: "{{ zbx_login_resp.json.result }}"

- name: Include per-record tasks
  include_tasks: per_record.yml
  loop: "{{ zbx_records }}"
  loop_control:
    loop_var: zbx_record


